# Generated by Django 3.0 on 2019-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
